# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Install Tor and other required packages
RUN apt-get update && \
    apt-get install -y nano tor telnet python3 python3-pip libevent-dev libssl-dev && \
    pip install requests stem pysocks

COPY torrc /etc/tor/torrc

# Copy the current directory contents into the container at /app
COPY . /app

# Expose the Tor control port
EXPOSE 9051

# Run the script when the container launches
# CMD ["sh", "-c", "tor -f /etc/tor/torrc && python3 ./helpers.py"]
CMD ["tor","-f","/etc/tor/torrc","&&","python3 helpers.py"]