# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Install Tor and other required packages
RUN apt-get update && \
    apt-get install -y tor && \
    pip install requests stem

# Copy the current directory contents into the container at /app
COPY . /app

# Expose the Tor control port
EXPOSE 9051

# Run the script when the container launches
CMD ["python", "./helpers.py"]
