name: Print Commit Changes

on:
  push:
    branches:
      - '*'

jobs:
  print_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print changes in commit
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)
          for file in $changed_files; do
              echo "Changes in file: $file"
              git diff HEAD^ HEAD -- "$file"
              echo "----------------------------------------"
          done
